run test

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,6 +1,7 @@
 name: main
 on: [push]
 jobs:
+
   build:
     runs-on: ubuntu-latest
     steps:
@@ -11,18 +12,16 @@ jobs:
       uses: actions/setup-node@v2
       with:
         node-version: '18'
-
+    
     - name: install package.json
       run: npm install
     
-      - name: Run test
+    - name: Run test
       run: |
         output=$(node dist/test.js)
-        exit_code=$?
+        exit_code=$output
 
         if [ $exit_code -ne 0 ]; then
-            echo "Error: The Node.js script failed with exit code $exit_code"
-            exit 1
+          echo "Error $exit_code"
+          exit 1
         fi
-
-      
