run test 1

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -17,11 +17,13 @@ jobs:
     
     - name: Run test
       run: |
-        output=$(node dist/test.js)
-        exit_code=$output
+      output=$(node dist/test.js)
+      # Capture the exit code of the previous command
+      exit_code=$output
 
-        if [ $exit_code -ne 0 ]; then
-          echo "Error $exit_code"
-          exit 1
-        fi
+      # Check the exit code to determine if there was an error
+      if [ $exit_code -ne 0 ]; then
+      echo "Error: The Node.js script failed with exit code $exit_code"
+      exit 1 # Exit the workflow with an error code
+      fi
 
