run

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -4,23 +4,29 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
-        
-      - name: Setup node.js
-        uses: actions/setup-node@v2
-        with:
-          node-version: '18'
-      
-      - name: Install dependencies
-        run: npm install
-        
-      - name: Run test
-        run: |
-          output=$(node dist/test.js)
-          exit_code=$output
+    - name: Checkout code
+      uses: actions/checkout@v2
+    
+    - name: Setup node.js
+      uses: actions/setup-node@v2
+      with:
+        node-version: '18'
 
-          if [ $exit_code -ne 0 ]; then
-            echo "Error: The Node.js script failed with exit code $exit_code"
-            exit 1
-          fi
+    - name: Install dependencies
+      run: npm install
+
+    - name: Check dist directory
+      run: ls dist/
+    
+    - name: Run test
+      run: |
+        output=$(node dist/test.js)
+        exist_code=$output
+
+        if [ $exit_code -ne 0 ]; then
+        echo "Error: The Node.js script failed with exit code $exit_code"
+        exit 1
+        fi
+    - name: Run test 2
+      run: |
+      
